# Generated by Django 4.0.1 on 2022-01-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='human_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='humans.human'),
        ),
        migrations.AddField(
            model_name='human',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='human',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
