# Generated by Django 4.0.1 on 2022-01-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0002_dog_age_dog_human_id_human_age_human_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='human_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humans.human'),
        ),
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='human',
            name='email',
            field=models.CharField(max_length=300),
        ),
    ]
