# Generated by Django 4.0.1 on 2022-01-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0003_alter_dog_age_alter_dog_human_id_alter_human_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='age',
            new_name='dog_age',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='name',
            new_name='dog_name',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='age',
            new_name='human_age',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='email',
            new_name='human_email',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='name',
            new_name='human_name',
        ),
        migrations.AlterModelTable(
            name='dog',
            table='dogs',
        ),
        migrations.AlterModelTable(
            name='human',
            table='humans',
        ),
    ]
