# Generated by Django 4.0.1 on 2022-01-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0004_rename_age_dog_dog_age_rename_name_dog_dog_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='human_id',
            new_name='human',
        ),
    ]
