# Generated by Django 4.0.1 on 2022-01-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0005_rename_human_id_dog_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='human_email',
            field=models.EmailField(max_length=300),
        ),
    ]
